server:
 port: 1111

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

zuul:
  routes:
    microservice: 
      path: /asset/**
      serviceId: asset-ws